name: 'Vitest evaluator'
description: 'Vitest evaluator action for javascript projects'
inputs:
  npm-start:
    description: 'Run npm start and waits to url before testing'
    default: false
  wait-for:
    description: 'Url that npm start command waits for'
    default: 'http://localhost:3000'
outputs:
  result:
    description: 'Vitest unit tests JSON results'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.npm-start }}
    - ${{ inputs.wait-for }}
